name: offline_posts_manager
description: "This app is called Offline Posts Manager. It uses Flutter for the UI and SQLite through the sqflite package for local data storage. The app allows users to add, read, update, and delete posts even without internet. I separated the code into model, database, screens, and widgets for clean architecture. I also handled database errors using try-catch and protected against invalid data when converting database rows into Post objects."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  path: ^1.9.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true